theme = "kanagawa-dragon-new"

[editor]
end-of-line-diagnostics = "hint"
completion-timeout = 0
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.inline-diagnostics]
cursor-line= "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-s = ":w!"
S-z = ":wq!"
S-q = ":q!"

[keys.insert]
C-space = "completion"
