# theme = "gruvbox"
# theme = "gruvbox-material"
# theme = "solarized_dark"
# theme = "base16_default_dark"
# theme = "kanagawa"
# theme = "kanagawa-dragon"
theme = "kanagawa-dragon-new"
# theme = "everforest_dark"
# theme = "rose_pine_moon"
# theme = "nord"
# theme = "nord-night"
# theme = "term16_dark"

[editor]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "block"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.inline-diagnostics]
cursor-line= "warning"

[keys.normal]
C-s = ":w!"
S-z = ":wq!"
S-q = ":q!"

[keys.insert]
C-space = "completion"
